### PR TITLE
Migrate tpb module to actual tpb

### PR DESCRIPTION
**Pull request by phil-bell**
## Status
**READY**

## Migrations
 NO

## Description
I've migrated The Pirate Bay module to use the API that thepiratebay.org uses. Meaning it will have the same results and we no londer need to webscrape. I've also added a "safe for work" filter to the module with `--sfw`.

## Impacted Areas in Application
List general components of the application that this PR will affect:

* `the_pirate_bay` module

### CODE REVIEW

**Comment by rachmadaniHaryono** [comment]
can you update the test? if not i can add to your branch later?

**Comment by phil-bell** [comment]
Yeah I can give it a go

**Comment by phil-bell** [comment]
@rachmadaniHaryono have fixed the tests locally, not sure whats happening with the CI tool? Is just saying its queued.

**Comment by rachmadaniHaryono** [comment]
pytest run fine on my machine so maybe it is just travisci

thank you for the pr

**Pull request merged**
