### PR TITLE
Flake8

### PR DESCRIPTION
**Pull request by Hendrikto**
Fix all flake8 errors.

### CODE REVIEW

**Comment by rachmadaniHaryono** [comment]
hi @hendrikto, can you also change the setup.cfg. i have exclude several error there. 

the flake8 pr should be completed when those flake8 test can be run without those config

**Comment by Hendrikto** [comment]
I removed the exceptions from the setup file but when I run flake8 now, I get this error:

    ./we_get/core/we_get.py:32:80: E501 line too long (90 > 79 characters)

But you set the max-line-length to 99. I do not now why this isn't recognized.

**Comment by rachmadaniHaryono** [comment]
can you check it once again? the travis show only E121 error

https://travis-ci.org/rachmadaniHaryono/we-get/jobs/229142282

>/home/travis/build/rachmadaniHaryono/we-get/setup.py:11:3: E121 continuation line under-indented for hanging indent


try to run the flake8 by following command `python -m pytest --flake8` in your virtual env

e: if you run `flake8`, your system`flake8`  instead of virtualenv `flake8` will be run, and project's `setup.cfg` will not be used

**Comment by Hendrikto** [comment]
Oh yeah, my bad. I just ran flake8 directly because I got `pytest.py: error: unrecognized arguments: --flake8
` which I fixed by installing pytest-flake8. Maybe we should put this in the README under "development dependencies" or something?

Everything should be fixed now.

**Comment by rachmadaniHaryono** [comment]
Current situation right now : 

 the packages required for testing is only explained on Travis yaml config. 

We can 

- add 'requirements-dev.txt' and add the package there or 
- add test section on  extras package. That way there will be no requirement-dev.txt for 

For testing guide : Maybe put a section on Readme on how to test it. 

Also please rebase this pr against master branch

**Comment by rachmadaniHaryono** [comment]
Thank you

**Pull request merged**
